---
# windows configuration of base image

  - name: create c:/temp
    win_file:
      path: c:/temp
      state: directory

  - name: modify hosts file
    win_template:
      src: hosts.j2
      dest: c:/windows/system32/drivers/etc/hosts

  - name: disable windows update
    win_service:
      name: wuauserv
      start_mode: manual
      state: stopped

  - name: disable hibernate
    win_regedit:
      key: HKLM:\System\CurrentControlSet\Control\Power
      value: HibernateEnabled
      data: 0
      datatype: dword

  - name: enable w32time service
    win_service:
      name: w32time
      state: started
      start_mode: auto

  - name: enable winrm service
    win_service:
      name: winrm
      state: started
      start_mode: auto

  - name: configure ntp
    win_regedit:
      key: HKLM:\System\CurrentControlSet\Services\W32Time\Parameters
      value: NtpServer
      data: "{{ntp_server}},0x08"
      datatype: string

  - name: create crash dump path
    win_file:
      path: "{{crash_path}}"
      state: directory

  - name: crash dumps regkey - crash path
    win_regedit:
      key: HKLM:\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps
      value: DumpFolder
      data: "{{crash_path}}"
      datatype: string

  - name: crash dumps regkeys
    win_regedit:
      key: HKLM:\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps"
      value: "{{item.v}}"
      data: "{{item.d}}"
      datatype: dword
    with_items:
    - { "v": "DumpCount", "d": "10" }
    - { "v": "DumpType", "d": "2" }
    - { "v": "CustomDumpFlags", "d": "0" }

  - name: disable windows error reporting
    win_service:
      name: wersvc
      state: stopped
      start_mode: disabled

  - name: disable windows firewall
    raw: "netsh advfirewall set allprofiles state off"

  - name: enable dns
    raw: "$i={{interface}};$i.setdnsserversearchorder('{{dns_server}}');"

  # installation of client
  - name: client install
    include: client.yml
    when: client is defined

  # modify system.yml to include system modification/updates
  - name: system modification
    include: system.yml

  - name: disable dns
    raw: "$i={{interface}};$i.setdnsserversearchorder('127.0.0.1');"

  - name: zeroize free space
    raw: "c:/tools/sysinternalssuite/sdelete.exe -z"
    when: compress is defined

  - name: shutdown host
    raw: "shutdown -s -t 1"
    ignore_errors: true
